language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
virtualenv:
  system_site_packages: true
before_install:
  - SITE_PKG_DIR=$VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/site-packages
  - rm -f $VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/no-global-site-packages.txt
  - sudo apt-get install python-numpy
  - sudo apt-get install python-scipy
install:
  - "sudo pip install -U pandas"
  - "sudo pip install -U scikit-learn"
  - "sudo pip install -U statsmodels"
  - "sudo pip install -U patsy"
  - "sudo pip install -U coveralls"
script:
  - nosetests --with-coverage --cover-package=category_encoders
after_success:
  - coveralls