language: python

cache:
  apt: true
  # We use three different cache directory
  # to work around a Travis bug with multi-platform cache
  directories:
  - $HOME/.cache/pip
  - $HOME/download
env:
  global:
    # Directory where tests are run from
    - TEST_DIR=/tmp/test_dir/
    - MODULE=category_encoders
  matrix:
    # The versions should match the minimal requirements in requirements.txt and setup.py
    - DISTRIB="conda" PYTHON_VERSION="2.7" CYTHON_VERSION="0.21"
      NUMPY_VERSION="1.12.1" PANDAS_VERSION="0.20.1" PATSY_VERSION="0.4.1"
      SCIKIT_VERSION="0.18.1" SCIPY_VERSION="0.18.1" STATSMODELS_VERSION="0.6.1"
    - DISTRIB="conda" PYTHON_VERSION="3.5" COVERAGE="true" CYTHON_VERSION="0.23.4"
      NUMPY_VERSION="1.12.1" PANDAS_VERSION="0.20.1" PATSY_VERSION="0.4.1"
      SCIKIT_VERSION="0.18.1" SCIPY_VERSION="0.18.1" STATSMODELS_VERSION="0.6.1"

install: source ci_scripts/install.sh
script: bash ci_scripts/test.sh
after_success: source ci_scripts/success.sh