name: "PyPI Packaging"
on:
  release:
    types: created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v1
      - name: Build package
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          python setup.py bdist_wheel sdist
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: willmcg4132
          password: ${{ secrets.pypi_password }}